# all team members have contributed in equal measure to this effort,
# Plot the regression lines for the attributes with the largest weights
# This is the batch gradient descent model trained on the full feature set,, 
#before and after regularization (both L1 and L2)
# 

import numpy as np
import matplotlib.pyplot as plt
 
from step_1 import train_linear_regression
from step_2 import train_ridge_regression
from step_3 import train_lasso_regression


# once again, here are the feature names
feature_names = [
    "fixed acidity",
    "volatile acidity",
    "citric acid",
    "residual sugar",
    "chlorides",
    "free sulfur dioxide",
    "total sulfur dioxide",
    "density",
    "pH",
    "sulphates",
    "alcohol",
    "is_red",
]


# load the arrays generated by step_0.py.
X_train = np.load("X_train.npy")
Y_train = np.load("Y_train.npy")

# Use the best Regularization parameters found in step_2.py and step_3.py to train the models again
Best_Lambda_Ridge = 0.001
Best_Alpha_Lasso = 0.001

# Train the models again using the best regularization parameters
w_before, mean_before, std_before, loss_history_before = train_linear_regression(X_train, Y_train)

w_l2, mean_l2, std_l2, loss_history_l2 = train_ridge_regression(X_train, Y_train, lambda_=Best_Lambda_Ridge)

w_l1, mean_l1, std_l1, loss_history_l1 = train_lasso_regression(X_train, Y_train, alpha=Best_Alpha_Lasso)

# ID the attribute with the largest absolute weight for the unregularized model, 
# we will visualize the regression line for this attribute before and after regularization
Feature_idx = np.argmax(np.abs(w_before[1:])) + 1  # +1 to account for the bias term at index 0
Feature_name = feature_names[Feature_idx - 1]  # -1 to account for the bias term at index 0

print(f"Largest absolute weight attribute (unregularized): {Feature_name}")
print(f"Before regularization weight: {w_before[Feature_idx]:.6f}")
print(f"After L2 regularization weight: {w_l2[Feature_idx]:.6f}")
print(f"After L1 regularization weight: {w_l1[Feature_idx]:.6f}")

# Predicted quality  as a single atrribute varies over "x_range", holding all other attributes at their mean values
#this gives a 2D slice through the full multivirate regression model, allowing us to visualize the effect of this single attribute on the predicted quality
def partial_regression_line(x_range, weights, feature_mean, feature_std, idx):
    scaled_x = (x_range - feature_mean[idx - 1]) / feature_std[idx - 1]
    return weights[0] + weights[idx] * scaled_x
 
# Raw values of the chosen attribute for the training set, to plot the scatter of the training data
x_raw = X_train[:, Feature_idx]
x_line = np.linspace(np.min(x_raw), np.max(x_raw), 100)

y_before = partial_regression_line(x_line, w_before, mean_before, std_before, Feature_idx)
y_l2 = partial_regression_line(x_line, w_l2, mean_l2, std_l2, Feature_idx)
y_l1 = partial_regression_line(x_line, w_l1, mean_l1, std_l1, Feature_idx)

# Plotting the regression lines for the attribute with the largest weight before and after regularization
fig, axes = plt.subplots(1, 3, figsize=(18, 5), sharey=True)
 
titles = [
    "Before regularization", "After L2 (Ridge)",
    "After L1 (Lasso)"
]
lines = [y_before, y_l2, y_l1]
colors = ["tab:blue", "tab:green", "tab:orange"]
 
for ax, title, y_line, color in zip(axes, titles, lines, colors):
    ax.scatter(x_raw, Y_train, s=8, alpha=0.15, color="gray", label="Training data")
    ax.plot(x_line, y_line, color=color, linewidth=2.5, label="Regression line")
    ax.set_title(title)
    ax.set_xlabel(Feature_name)
    ax.legend(loc="upper right", fontsize=8)
 
axes[0].set_ylabel("quality")
fig.suptitle(
    f"Batch gradient descent: regression line for '{Feature_name}' "
    f"(largest |weight| attribute), before vs. after regularization",
    fontsize=12,
)
plt.tight_layout(rect=[0, 0, 1, 0.94])
plt.savefig("step_4_regression_lines.png", dpi=150)
print("\nSaved plot to step_4_regression_lines.png")
#also, produce a single combined overlay for direct visual comparison.
fig2, ax2 = plt.subplots(figsize=(8, 6))
ax2.scatter(x_raw, Y_train, s=8, alpha=0.12, color="gray", label="Training data")
ax2.plot(x_line, y_before, color="tab:blue", linewidth=2.5, label="Before regularization")
ax2.plot(x_line, y_l2, color="tab:green", linewidth=2.5, label="After L2 (Ridge)")
ax2.plot(x_line, y_l1, color="tab:orange", linewidth=2.5, linestyle="--", label="After L1 (Lasso)")
ax2.set_xlabel(Feature_name)
ax2.set_ylabel("quality")
ax2.set_title(f"Regression line for '{Feature_name}' across regularization settings")
ax2.legend()
plt.tight_layout()
plt.savefig("step_4_regression_lines_overlay.png", dpi=150)
print("Saved plot to step_4_regression_lines_overlay.png")

