# all team members have contributed in equal measure to this effort,
# Luca Toth, Brayden Molinyawe
# Train and test each model without regularization

import numpy as np

def mse(y_true, y_pred):
	# Return the mean squared error
	# Measure the average squared difference between the real and predicted values
	return np.mean((y_true - y_pred) ** 2)

def train_linear_regression(X_train, Y_train, learning_rate=0.01, epochs=10000):
	# Train linear regression with batch gradient descent and no regularization.
	# Standardize non-bias features so one learning rate works for every feature
	# The first column is the bias column, so it must remain equal to one
	feature_mean = X_train[:, 1:].mean(axis=0)
	feature_std = X_train[:, 1:].std(axis=0)
	feature_std[feature_std == 0] = 1 

	X_scaled = X_train.copy().astype(float)
	X_scaled[:, 1:] = (X_scaled[:, 1:] - feature_mean) / feature_std

	# Start with a weight of zero for the bias and every feature
	weights = np.zeros(X_scaled.shape[1])
	loss_history = []
	sample_count = X_scaled.shape[0]

	for _ in range(epochs):
		# Predict every training example at once using matrix multiplication
		predictions = X_scaled @ weights
		errors = predictions - Y_train
		gradient = (2 / sample_count) * (X_scaled.T @ errors)

		# Move the weights opposite the gradient to reduce the training loss
		weights -= learning_rate * gradient
		loss_history.append(mse(Y_train, predictions))

	return weights, feature_mean, feature_std, loss_history


# Train linear regression with mini-batch gradient descent and no regularization
def train_minibatch_linear_regression(
	X_train, Y_train, learning_rate=0.01, epochs=100, batch_size=32, seed=42
):
	# Use the training-set statistics for all mini-batches and later evaluations
	feature_mean = X_train[:, 1:].mean(axis=0)
	feature_std = X_train[:, 1:].std(axis=0)
	feature_std[feature_std == 0] = 1

	X_scaled = X_train.copy().astype(float)
	X_scaled[:, 1:] = (X_scaled[:, 1:] - feature_mean) / feature_std

	# Initialize one weight for the bias and one weight for every feature
	weights = np.zeros(X_scaled.shape[1])
	loss_history = []
	random_generator = np.random.default_rng(seed)

	for _ in range(epochs):
		# Randomly reorder the data so each epoch uses different mini batches
		shuffled_indices = random_generator.permutation(X_scaled.shape[0])

		for start in range(0, X_scaled.shape[0], batch_size):
			batch_indices = shuffled_indices[start : start + batch_size]
			X_batch = X_scaled[batch_indices]
			Y_batch = Y_train[batch_indices]
			batch_count = X_batch.shape[0]

			# predict the outputs for the selected mini-batch
			batch_predictions = X_batch @ weights
			# compute the same MSE gradient using this mini-batch
			batch_errors = batch_predictions - Y_batch
			gradient = (2 / batch_count) * (X_batch.T @ batch_errors)
			# update the weights using the learning rate
			weights -= learning_rate * gradient

		# use the complete training set to track progress per epoch
		full_predictions = X_scaled @ weights
		loss_history.append(mse(Y_train, full_predictions))

	return weights, feature_mean, feature_std, loss_history

# Add a bias column and apply training-set feature scaling
def add_bias_and_scale(X, feature_mean, feature_std):
	# Apply the same transformation learned from the training set to new data.
	X_scaled = X.astype(float).copy()
	X_scaled[:, 1:] = (X_scaled[:, 1:] - feature_mean) / feature_std
	return X_scaled

# Load the arrays generated by step_0.py
X_train = np.load("X_train.npy")
Y_train = np.load("Y_train.npy")
X_valid = np.load("X_valid.npy")
Y_valid = np.load("Y_valid.npy")
X_test = np.load("X_test.npy")
Y_test = np.load("Y_test.npy")

# Scale validation and test faetures without recalculating their own statistics
batch_weights, batch_mean, batch_std, batch_loss_history = train_linear_regression(
	X_train, Y_train
)

mini_weights, mini_mean, mini_std, mini_loss_history = (
	train_minibatch_linear_regression(X_train, Y_train)
)

# Print training, validation, and test MSE for one trained model
def evaluate_model(model_name, weights, feature_mean, feature_std, loss_history):
	
	# Apply only the training-set scaling statistics to unseen data
	X_valid_scaled = add_bias_and_scale(X_valid, feature_mean, feature_std)
	X_test_scaled = add_bias_and_scale(X_test, feature_mean, feature_std)

	# Evaluate weights on data that was not used to update them
	valid_predictions = X_valid_scaled @ weights
	test_predictions = X_test_scaled @ weights

	print(f"\n{model_name}")
	print("Initial training MSE:", loss_history[0])
	print("Final training MSE:", loss_history[-1])
	print("Validation MSE:", mse(Y_valid, valid_predictions))
	print("Test MSE:", mse(Y_test, test_predictions))

# Report results for both required unregularized gradient-descent models
evaluate_model(
	"Batch gradient descent",
	batch_weights,
	batch_mean,
	batch_std,
	batch_loss_history,
)
evaluate_model(
	"Mini-batch gradient descent",
	mini_weights,
	mini_mean,
	mini_std,
	mini_loss_history,
)
