# Train and test each model with L2 Regularization (Ridge Regression).

import numpy as np

def mse(y_true, y_pred):
    """Return the mean squared error."""
    return np.mean((y_true - y_pred) ** 2)


def train_ridge_regression(
    X_train, Y_train, learning_rate=0.01, epochs=10000, lambda_=0.1
):
    """Train linear regression with batch gradient descent and L2 regularization."""

    # Standardize non-bias features so one learning rate works for every feature.
    # The first column is the bias column, so it must remain equal to one.
    feature_mean = X_train[:, 1:].mean(axis=0)
    feature_std = X_train[:, 1:].std(axis=0)
    feature_std[feature_std == 0] = 1

    X_scaled = X_train.copy().astype(float)
    X_scaled[:, 1:] = (X_scaled[:, 1:] - feature_mean) / feature_std

    # Start with a weight of zero for the bias and every feature.
    weights = np.zeros(X_scaled.shape[1])
    loss_history = []
    sample_count = X_scaled.shape[0]

    for _ in range(epochs):

        # Make predictions
        predictions = X_scaled @ weights

        # Calculate prediction errors
        errors = predictions - Y_train

        # Gradient of the MSE
        mse_gradient = (2 / sample_count) * (X_scaled.T @ errors)

        # Gradient of the L2 regularization term
        regularization_gradient = 2 * lambda_ * weights

        # Total gradient
        gradient = mse_gradient + regularization_gradient

        # Update weights
        weights -= learning_rate * gradient

        # Store the training MSE
        loss_history.append(mse(Y_train, predictions))

    return weights, feature_mean, feature_std, loss_history


def scale_new_data(X, feature_mean, feature_std):
    """Apply the training-set scaling to validation or test data."""

    X_scaled = X.astype(float).copy()
    X_scaled[:, 1:] = (X_scaled[:, 1:] - feature_mean) / feature_std

    return X_scaled


# Load arrays generated by step_0.py.
X_train = np.load("X_train.npy")
Y_train = np.load("Y_train.npy")
X_valid = np.load("X_valid.npy")
Y_valid = np.load("Y_valid.npy")
X_test = np.load("X_test.npy")
Y_test = np.load("Y_test.npy")


# Try several values of lambda.
lambda_values = [0.0001, 0.001, 0.01, 0.1, 1.0, 10.0]

best_lambda = None
best_validation_mse = float("inf")
best_weights = None
best_mean = None
best_std = None
best_loss_history = None


for lambda_ in lambda_values:

    weights, feature_mean, feature_std, loss_history = train_ridge_regression(
        X_train,
        Y_train,
        lambda_=lambda_
    )

    # Scale the validation data using the training-set statistics.
    X_valid_scaled = scale_new_data(
        X_valid,
        feature_mean,
        feature_std
    )

    # Make validation predictions.
    valid_predictions = X_valid_scaled @ weights

    # Calculate validation MSE.
    validation_mse = mse(Y_valid, valid_predictions)

    print(f"lambda = {lambda_}")
    print(f"Validation MSE = {validation_mse:.4f}")
    print()

    # Keep the model with the lowest validation MSE.
    if validation_mse < best_validation_mse:
        best_validation_mse = validation_mse
        best_lambda = lambda_
        best_weights = weights
        best_mean = feature_mean
        best_std = feature_std
        best_loss_history = loss_history


# Print the best lambda.
print("Best lambda:", best_lambda)
print("Best validation MSE:", best_validation_mse)


# Feature names corresponding to the columns of X.
feature_names = [
    "fixed acidity",
    "volatile acidity",
    "citric acid",
    "residual sugar",
    "chlorides",
    "free sulfur dioxide",
    "total sulfur dioxide",
    "density",
    "pH",
    "sulphates",
    "alcohol",
    "is_red"
]


# Print the weights of the best ridge model.
print("\nWeights from the best ridge model:")

print(f"bias: {best_weights[0]:.6f}")

for name, weight in zip(feature_names, best_weights[1:]):
    print(f"{name}: {weight:.6f}")


# Find the feature with the smallest absolute weight.
# Exclude the bias term at index 0.
smallest_weight_index = np.argmin(np.abs(best_weights[1:])) + 1

feature_to_remove = feature_names[smallest_weight_index - 1]

print("\nFeature to remove:", feature_to_remove)
print("Weight:", best_weights[smallest_weight_index])


# Remove the selected feature from the training, validation,
# and test sets.
X_train_reduced = np.delete(
    X_train,
    smallest_weight_index,
    axis=1
)

X_valid_reduced = np.delete(
    X_valid,
    smallest_weight_index,
    axis=1
)

X_test_reduced = np.delete(
    X_test,
    smallest_weight_index,
    axis=1
)


# Retrain using batch gradient descent on the reduced feature set.
# lambda_=0 means there is no regularization.
reduced_weights, reduced_mean, reduced_std, reduced_loss_history = (
    train_ridge_regression(
        X_train_reduced,
        Y_train,
        lambda_=0.0
    )
)


# Evaluate the reduced model on the validation and test sets.
X_valid_reduced_scaled = scale_new_data(
    X_valid_reduced,
    reduced_mean,
    reduced_std
)

X_test_reduced_scaled = scale_new_data(
    X_test_reduced,
    reduced_mean,
    reduced_std
)

valid_predictions = X_valid_reduced_scaled @ reduced_weights
test_predictions = X_test_reduced_scaled @ reduced_weights


print("\nReduced model")
print("Initial training MSE:", reduced_loss_history[0])
print("Final training MSE:", reduced_loss_history[-1])
print("Validation MSE:", mse(Y_valid, valid_predictions))
print("Test MSE:", mse(Y_test, test_predictions))